# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: showtime.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eshowtime.proto\",\n\x0cShowtimeData\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"\x1c\n\x0cShowtimeDate\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"\x1b\n\x08MoviesId\x12\x0f\n\x07movieid\x18\x01 \x03(\t\"\x0f\n\rEmptyShowtime2\xa7\x01\n\x08Showtime\x12\x34\n\x0fGetAllShowtimes\x12\x0e.EmptyShowtime\x1a\r.ShowtimeData\"\x00\x30\x01\x12/\n\x0fGetMoviesByDate\x12\r.ShowtimeDate\x1a\t.MoviesId\"\x00\x30\x01\x12\x34\n\x12GetMoviesByDateTmp\x12\r.ShowtimeDate\x1a\r.ShowtimeData\"\x00\x62\x06proto3')



_SHOWTIMEDATA = DESCRIPTOR.message_types_by_name['ShowtimeData']
_SHOWTIMEDATE = DESCRIPTOR.message_types_by_name['ShowtimeDate']
_MOVIESID = DESCRIPTOR.message_types_by_name['MoviesId']
_EMPTYSHOWTIME = DESCRIPTOR.message_types_by_name['EmptyShowtime']
ShowtimeData = _reflection.GeneratedProtocolMessageType('ShowtimeData', (_message.Message,), {
  'DESCRIPTOR' : _SHOWTIMEDATA,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:ShowtimeData)
  })
_sym_db.RegisterMessage(ShowtimeData)

ShowtimeDate = _reflection.GeneratedProtocolMessageType('ShowtimeDate', (_message.Message,), {
  'DESCRIPTOR' : _SHOWTIMEDATE,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:ShowtimeDate)
  })
_sym_db.RegisterMessage(ShowtimeDate)

MoviesId = _reflection.GeneratedProtocolMessageType('MoviesId', (_message.Message,), {
  'DESCRIPTOR' : _MOVIESID,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:MoviesId)
  })
_sym_db.RegisterMessage(MoviesId)

EmptyShowtime = _reflection.GeneratedProtocolMessageType('EmptyShowtime', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYSHOWTIME,
  '__module__' : 'showtime_pb2'
  # @@protoc_insertion_point(class_scope:EmptyShowtime)
  })
_sym_db.RegisterMessage(EmptyShowtime)

_SHOWTIME = DESCRIPTOR.services_by_name['Showtime']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SHOWTIMEDATA._serialized_start=18
  _SHOWTIMEDATA._serialized_end=62
  _SHOWTIMEDATE._serialized_start=64
  _SHOWTIMEDATE._serialized_end=92
  _MOVIESID._serialized_start=94
  _MOVIESID._serialized_end=121
  _EMPTYSHOWTIME._serialized_start=123
  _EMPTYSHOWTIME._serialized_end=138
  _SHOWTIME._serialized_start=141
  _SHOWTIME._serialized_end=308
# @@protoc_insertion_point(module_scope)
