# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import booking_pb2 as booking__pb2


class BookingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBookingByUserid = channel.unary_unary(
                '/Booking/GetBookingByUserid',
                request_serializer=booking__pb2.BookingUserId.SerializeToString,
                response_deserializer=booking__pb2.BookingObject.FromString,
                )
        self.AddBookingByUserid = channel.unary_unary(
                '/Booking/AddBookingByUserid',
                request_serializer=booking__pb2.OneBooking.SerializeToString,
                response_deserializer=booking__pb2.NotificationMessageBooking.FromString,
                )


class BookingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBookingByUserid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBookingByUserid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBookingByUserid': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookingByUserid,
                    request_deserializer=booking__pb2.BookingUserId.FromString,
                    response_serializer=booking__pb2.BookingObject.SerializeToString,
            ),
            'AddBookingByUserid': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBookingByUserid,
                    request_deserializer=booking__pb2.OneBooking.FromString,
                    response_serializer=booking__pb2.NotificationMessageBooking.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Booking', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Booking(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBookingByUserid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Booking/GetBookingByUserid',
            booking__pb2.BookingUserId.SerializeToString,
            booking__pb2.BookingObject.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddBookingByUserid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Booking/AddBookingByUserid',
            booking__pb2.OneBooking.SerializeToString,
            booking__pb2.NotificationMessageBooking.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
