# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: booking.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\"6\n\rBookingObject\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x15\n\x05\x64\x61tes\x18\x02 \x03(\x0b\x32\x06.Dates\"&\n\x05\x44\x61tes\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0f\n\x07movieid\x18\x02 \x03(\t\";\n\nOneBooking\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x0f\n\x07movieid\x18\x03 \x01(\t\"-\n\x1aNotificationMessageBooking\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\rBookingUserId\x12\x0e\n\x06userid\x18\x01 \x01(\t2\x83\x01\n\x07\x42ooking\x12\x36\n\x12GetBookingByUserid\x12\x0e.BookingUserId\x1a\x0e.BookingObject\"\x00\x12@\n\x12\x41\x64\x64\x42ookingByUserid\x12\x0b.OneBooking\x1a\x1b.NotificationMessageBooking\"\x00\x62\x06proto3')



_BOOKINGOBJECT = DESCRIPTOR.message_types_by_name['BookingObject']
_DATES = DESCRIPTOR.message_types_by_name['Dates']
_ONEBOOKING = DESCRIPTOR.message_types_by_name['OneBooking']
_NOTIFICATIONMESSAGEBOOKING = DESCRIPTOR.message_types_by_name['NotificationMessageBooking']
_BOOKINGUSERID = DESCRIPTOR.message_types_by_name['BookingUserId']
BookingObject = _reflection.GeneratedProtocolMessageType('BookingObject', (_message.Message,), {
  'DESCRIPTOR' : _BOOKINGOBJECT,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:BookingObject)
  })
_sym_db.RegisterMessage(BookingObject)

Dates = _reflection.GeneratedProtocolMessageType('Dates', (_message.Message,), {
  'DESCRIPTOR' : _DATES,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:Dates)
  })
_sym_db.RegisterMessage(Dates)

OneBooking = _reflection.GeneratedProtocolMessageType('OneBooking', (_message.Message,), {
  'DESCRIPTOR' : _ONEBOOKING,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:OneBooking)
  })
_sym_db.RegisterMessage(OneBooking)

NotificationMessageBooking = _reflection.GeneratedProtocolMessageType('NotificationMessageBooking', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFICATIONMESSAGEBOOKING,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:NotificationMessageBooking)
  })
_sym_db.RegisterMessage(NotificationMessageBooking)

BookingUserId = _reflection.GeneratedProtocolMessageType('BookingUserId', (_message.Message,), {
  'DESCRIPTOR' : _BOOKINGUSERID,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:BookingUserId)
  })
_sym_db.RegisterMessage(BookingUserId)

_BOOKING = DESCRIPTOR.services_by_name['Booking']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOKINGOBJECT._serialized_start=17
  _BOOKINGOBJECT._serialized_end=71
  _DATES._serialized_start=73
  _DATES._serialized_end=111
  _ONEBOOKING._serialized_start=113
  _ONEBOOKING._serialized_end=172
  _NOTIFICATIONMESSAGEBOOKING._serialized_start=174
  _NOTIFICATIONMESSAGEBOOKING._serialized_end=219
  _BOOKINGUSERID._serialized_start=221
  _BOOKINGUSERID._serialized_end=252
  _BOOKING._serialized_start=255
  _BOOKING._serialized_end=386
# @@protoc_insertion_point(module_scope)
